# Generated by Django 4.2.7 on 2024-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_food_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='status',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
