# Generated by Django 4.2.7 on 2024-05-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_room_no_authority_phone_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
