# Generated by Django 4.2.7 on 2024-05-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_authority_certificate_food_hostel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
