# Generated by Django 4.1.5 on 2023-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='value',
            new_name='data',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
